spring.application.name=blogging-platform-api

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_platform
spring.datasource.username=blog_user
spring.datasource.password=blog_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update